import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import Feed from "~/components/feed";
import { PostLayout } from "~/components/layout";
import { LoadingPage } from "~/components/loading";
import { api } from "~/utils/api";

export default function Home() {

  const { user } = useUser();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // const { data, isLoading } = api.posts.getAll.useQuery();

  // if(!data || isLoading) return <LoadingPage />


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostLayout>
        <div>
        <Feed />
      </div>
    </PostLayout>
    </>
  );
}
