import Head from "next/head";
import { PostLayout } from "~/components/layout";

export default function Create() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostLayout>
        <div >
          Create Page
      </div>
    </PostLayout>
    </>
  );
}
