import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { LoadingPage } from "~/components/loading";
import { api } from "~/utils/api";

export default function Feed() {

  const { user } = useUser();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  console.log('hello', hello.data);
  const { data, isLoading } = api.posts.getAll.useQuery();

  if(!data || isLoading) return <LoadingPage />

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className="flex p-4 pl-16 gap-10 border-t-2 border-black">
   {[...data]?.map(({post, author}) => (
    <div key={post.id} className = "w-80">
      <Link  href={{
    pathname: `/post/${post.id}`,
  }} key={post.id} >
    <div>
    <Image src={post.imageUrl}
     alt="car!" width="480" height ="320" 
     quality={75}
     priority={true}/>
     </div>
  <div className="card-body p-5 overflow-hidden ">
    <h2 className="card-title">{post.title}</h2>
  </div>
      </Link>
    </div>
   ))}
  </div>
    </>
  );
}
