import { UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { LoadingPage } from "~/components/loading";
import { api } from "~/utils/api";

export default function Feed() {

  const { user } = useUser();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data, isLoading } = api.posts.getAll.useQuery();

  if(!data || isLoading) return <LoadingPage />

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  {/* <div >
    <img src = {user?.profileImageUrl} alt="profile_pic" className = "h-12 w-12 rounded-full"/>
  </div> */}
  <div className="flex flex-wrap">
   {[...data]?.map(({post, author}) => (
    <div key={post.id} className = "space-x-4">
    <Link href={`/post/${post.id}`} key={post.id}>
    {/* <div key={post.id} className="text-white txt-lg">
      {post.title}
      {post.authorId}
      </div> */}
{/* <div className="card w-96 glass bg-white flex gap-3"> */}
  <figure className="w-72 h-48">
    <img src="https://cdn.discordapp.com/attachments/416094051339862016/1100205709133615164/wenatchee_lake.JPG" alt="car!" className="w-60 h-40"/>
  </figure>
  <div className="card-body">
    <h2 className="card-title">{post.title}</h2>
    <p>How to park your car at your garage?</p>
  </div>
{/* </div> */}
      </Link>
    </div>
   ))}
  </div>
    </>
  );
}
