import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { LoadingPage } from "~/components/loading";
import { api } from "~/utils/api";

export default function TopFeed() {

  const { data, isLoading } = api.posts.getAll.useQuery();
//   const recentData = data?.slice(0,3);

  if(!data || isLoading) return <LoadingPage />

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className="flex p-4 m-4 gap-10 border-t border-black">
    <div className = "w-1/2">
        {data[0]?.post.id && <Link href={`/post/${data[0]?.post.id}`}>
                    <div>
                        <Image src={data[0]?.post.imageUrl ?? ''}
                        alt="car!" width="720" height ="320" 
                        quality={75}
                        priority={true}/>
                    </div>
                    <div className="pt-2">
                        <h2 className="font-medium">{data[0]?.post.title}</h2>
                    </div>
        </Link>}
    </div>
    <div className="flex flex-col items-start space-y-52">
        <div className= "w-100 h-32">
            {data[1]?.post.id && <Link href={`/post/${data[1]?.post.id}`}>
                    <div>
                        <Image src={data[1]?.post.imageUrl ?? ''}
                        alt="car!" width="400" height ="128" 
                        quality={75}
                        priority={true}/>
                    </div>
                    <div className="w-80 overflow-auto pt-2">
                        <h2 className="font-medium">{data[1]?.post.title}</h2>
                    </div>
            </Link>}
        </div>
        <div className="flex space-x-4">
            <div className="w-48 h-16">
                {data[2]?.post.id && <Link href={`/post/${data[2]?.post.id}`}>
                        <div>
                            <Image src={data[2]?.post.imageUrl ?? ''}
                            alt="car!" width="192" height ="64" 
                            quality={75}
                            priority={true}/>
                        </div>
                        <div className="pt-2">
                            <h2 className="font-medium ">{data[2]?.post.title}</h2>
                        </div>
                    </Link>}
            </div>
            <div className="w-48 h-16">
                {data[2]?.post.id &&<Link href={`/post/${data[2]?.post.id}`}>
                        <div>
                            <Image src={data[2]?.post.imageUrl ?? ''}
                            alt="car!" width="192" height ="64" 
                            quality={75}
                            priority={true}/>
                        </div>
                        <div className="pt-2">
                            <h2 className="font-medium">{data[2]?.post.title}</h2>
                        </div>
                </Link>}
            </div>
        </div>
    </div>
    <div className="rounded border border-black w-64 h-108">
       {/* something goes in the box */}
    </div>
  </div>
    </>
  );
}
